### ISSUE TITLE
Nuevo controlador static_pages

### ISSUE THREAD

**Issue by alexisraca** [alexisraca/Icaro#1]
@silverfenix13 

- Crea un controlador que se llame static pages y agrega las rutas a config/routes

- resources :static_pages 

- asigna el root hacia static_pages#index

- crea la vista index

- recuerda crear primero tu gemset, correr bundle install y agregar los datos de tu base de datos local al archivo database.yml

tip: en el sublime puedes buscar un archivo apretando ctrl + r  y borrando el @ que sale, luego escribe el nombre del archivo y te da a elegir la ruta donde se encuentra por que puede encontrarte varios similares, cuando lo abras puedes darle click derecho y ponerle "mostrar en la barra lateral o sidebar" y abre todo el arbol de archivos automaticamente.

**Comment by silverfenix13** [comment]
hice los controladores la ruta pero me dice que hay algo mal aunque lo hice como antes cree la visat el gemset hice la gema llamada icaro

**Comment by silverfenix13** [comment]
https://github.com/alexisraca/Icaro/pull/2
